Repository seontechnologies/seon-sdk-flutter-plugin, pull requests merged in 2024-12, with the labels that each got.

#11 master -> develop backport (v1.0.1)
  CHANGELOG.md
  example/ios/Podfile.lock
  ios/seon_sdk_flutter_plugin.podspec
  pubspec.yaml
Labels: BACKPORT

#12 DEF-1677 - Add geofencing logic to Flutter wrapper
  CHANGELOG.md
  README.md
  android/build.gradle
  android/src/main/kotlin/io/seon/seon_sdk_flutter_plugin/SeonSdkFlutterPlugin.kt
  example/ios/Podfile.lock
  example/ios/Runner.xcodeproj/project.pbxproj
  example/lib/main.dart
  example/pubspec.lock
  ios/Classes/SeonSdkFlutterPlugin.swift
  ios/seon_sdk_flutter_plugin.podspec
  lib/seon_sdk_flutter_plugin.dart
  lib/seon_sdk_flutter_plugin_method_channel.dart
  lib/seon_sdk_flutter_plugin_platform_interface.dart
  lib/seon_sdk_geolocation_config.dart
  lib/seon_sdk_geolocation_config_builder.dart
  pubspec.yaml
  test/seon_sdk_flutter_plugin_test.dart
Labels: FEATURE

#13 Release/1.1.0
  CHANGELOG.md
  README.md
  android/build.gradle
  android/src/main/kotlin/io/seon/seon_sdk_flutter_plugin/SeonSdkFlutterPlugin.kt
  example/ios/Podfile.lock
  example/ios/Runner.xcodeproj/project.pbxproj
  example/lib/main.dart
  example/pubspec.lock
  ios/Classes/SeonSdkFlutterPlugin.swift
  ios/seon_sdk_flutter_plugin.podspec
  lib/seon_sdk_flutter_plugin.dart
  lib/seon_sdk_flutter_plugin_method_channel.dart
  lib/seon_sdk_flutter_plugin_platform_interface.dart
  lib/seon_sdk_geolocation_config.dart
  lib/seon_sdk_geolocation_config_builder.dart
  pubspec.yaml
  test/seon_sdk_flutter_plugin_test.dart
Labels: RELEASE
