Repository seontechnologies/seon-sdk-flutter-plugin, pull requests merged in 2025-09, with the labels that each got.

#17 DEF-2595 - Bump version and update documentation
  CHANGELOG.md
  example/ios/Podfile.lock
  example/pubspec.lock
  ios/seon_sdk_flutter_plugin.podspec
  pubspec.yaml
Labels: DOCUMENTATION

#19 DEF-2597 - Update Android example app's build tools
  android/build.gradle
  example/android/app/build.gradle
  example/android/gradle.properties
  example/android/gradle/wrapper/gradle-wrapper.properties
  example/android/settings.gradle
  example/pubspec.lock
Labels: FEATURE

#20 master -> develop backport (v1.2.0)
  CHANGELOG.md
  android/build.gradle
  example/android/app/build.gradle
  example/android/gradle.properties
  example/android/gradle/wrapper/gradle-wrapper.properties
  example/android/settings.gradle
  example/ios/Podfile.lock
  example/pubspec.lock
  ios/seon_sdk_flutter_plugin.podspec
  pubspec.yaml
Labels: BACKPORT

#22 Release/1.2.1
  README.md
  example/ios/Flutter/AppFrameworkInfo.plist
  example/ios/Podfile
  example/ios/Podfile.lock
  example/ios/Runner.xcodeproj/project.pbxproj
  example/pubspec.lock
  ios/seon_sdk_flutter_plugin.podspec
  pubspec.yaml
Labels: RELEASE

#23 Update CHANGELOG.md
  CHANGELOG.md
Labels: RELEASE
